# Docker compose script to run dev environment
version: '3'
services:

  mongo:
    image: mongo
    environment:
      - MONGODB_INITDB_DATABASE=auth
    ports:
    - "27017:27017"
    logging:
      driver: none

  auth:
    build:
      dockerfile: dockerfiles/Dockerfile.dev
      context: ../
    depends_on:
      - "mongo"
    environment:
      - SECRET=secret
      - PORT=5000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_NAME=auth
    ports:
    - "5000:5000"